repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.4'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
