language: python
sudo: required
services:
- docker        
python:
- 3.7
env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1
  - secure: Fb/yN5d5yJsl11Eu55xDE20tXuq/9xFNMw+nsTxQ6ydNW2j07K+BnMVhK189jOrSOQegZyljTdSE/KNCrOYKyqSpR0c917INmkjOMYgsxqlkgxLFfJY65yF+vpI6T+wqJspXKcqEQKyfJO5LFjHXbw23lXBqq5Jok4NdoJ0Eqy2Y0Bcn4WxkUMIOJYxpTsQCVmRin+0YnEfYHxLt5jIYP0fQdBQuqBj3a51ZMIq4WM5TmUNS9TLQsi8/q+KCmUwG7vIuiBfzBpgL3a89NyA2l6zdyswRBXinP5mrUi5LHDm7c2BO+t9kO2XkS8QrkX7YkUJwmVvORKsIWPqlYLkzhYtZsWoyI7SaeyGY2DB4g+ThkaZasmVp89fG87po8KDgOsY9k0o3A+6/4wcGaHpHbCKqd/Fzkh8isPwxJpVnUDFCMPRf3vYekffGRysI2YIG01Glx8S4kH8rwvDib5SPAQq3spccZupX+PcPhv0c8wTpRUk7SNbs6GGOGxDNkOcdS4dbPKyCgbPorjPeX+1a3QoNwGE+JuBNb5wlKjNqdbDUGv+biILU11dr/62BuoLndhcRG9yENSEsnWo8qb/IRh52F3jPEcWvpOUKhQAvbMhMgcOMTvxOQQRs78qjpKiW2aGt/pnsDlBGq90ib/cMKuav1N5TsHyDy/60M/M4XUE=
before_install:
- docker build -t bachmann1234/thrift-explorer .
install:
- pip install pipenv coveralls
- pipenv install --dev --three
script:
- pipenv run python -m pytest -v --cov-config .coveragerc --cov=thrift_explorer/ tests
after_success:
- coveralls
notifications:
  on_success: change
  on_failure: always
deploy:
  - provider: pypi 
    username: matt.bachmann
    password:
      secure: Nx20xAMS0XzikdOFVVQnIj0XHBbkYVLrWbrWErP4c9s154bJaxtBs2nUsCOl8Q60aEFYJyBIH4rvvrU+CPxjBM0UQNeQzXjn9kOL9gFm4vo/x1EtcXTdgX7YHkstbRYYM4ZkjdtJK//aMigW2eXrc0eWIZWS1RGIDvt7+vWarICeBWZYbwSwpEbvl/R2wLKEgJ9foIhVQ3juRytQm/LwtvN/KdBpBccIfenKQj27uNIWekJfADvT8hTZxZcyzghZ680gAvemxa3YTdZlGqzbk/E/PAXBPuITQrjkq0I9+jTBwpb/qqAS4zt3dyM+BgOogqYC3TE3r+qXZm2ZEcR9OvXMqxGe9WIndVSCIBeSUfndeYZFaMV/PdOvzxoYa4H5SRBR5qkQ6MMZZR4k/Cg42p0zlqhHdSaQpssMPD7iEWajn3OPzUp9/V4fk88Pcx7yQwjuq9NFg4hhqqVwz/BU15QQlRLT8XGMK6nyz858Jq9+yVQeLEizZLjVtysZ1M3tnSwShfAXY3WD2BW5wIqOjoPsFB8SbQ2sS15RcDNZXw5XLWNuFzsgkP4zUA3EQMtexR+8lKbKlyJTcglPeFqaXmbuXHlO/iGH/vPXaYhC2d6qbaE9AdlRvwx2N7dPcGvhjv45Sb025/8tu11puZqdoLBpF+Wz4DZg+T5ii1X+ZfE=
    on:
      tags: true
  - provider: script 
    script: bash docker_push
    on:
      tags: true
