language: python
python:
  - "3.7-dev"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install --dev --three
script:
  - pipenv shell
  - python -m pytest --cov=thrift_explorer/ tests