#!/bin/bash
VERSION=$(cat setup.py | grep "VERSION " | cut -d " " -f 3)
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag bachmann1234/thrift-explorer:latest  bachmann1234/thrift-explorer:${VERSION}
docker push bachmann1234/thrift-explorer 
