FROM python:3.7.0
MAINTAINER Matt Bachmann <bachmann.matt@gmail.com>

RUN apt-get update
RUN apt-get install -y gunicorn
RUN pip install --trusted-host pypi.python.org . 

EXPOSE 80
CMD ["/usr/bin/gunicorn", "-w", "2", "-b", "0.0.0.0:80", "thrift_explorer:app"]